---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-a2a-io-v1-a2aagent
  failurePolicy: Fail
  name: ma2aagent.kb.io
  rules:
  - apiGroups:
    - a2a.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - a2aagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-a2a-io-v1-a2aregistry
  failurePolicy: Fail
  name: ma2aregistry.kb.io
  rules:
  - apiGroups:
    - a2a.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - a2aregistries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-a2a-io-v1-a2aagent
  failurePolicy: Fail
  name: va2aagent.kb.io
  rules:
  - apiGroups:
    - a2a.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - a2aagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-a2a-io-v1-a2aregistry
  failurePolicy: Fail
  name: va2aregistry.kb.io
  rules:
  - apiGroups:
    - a2a.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - a2aregistries
  sideEffects: None
