---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - a2a.io
  resources:
  - a2aagents
  - a2aregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - a2a.io
  resources:
  - a2aagents/finalizers
  - a2aregistries/finalizers
  verbs:
  - update
- apiGroups:
  - a2a.io
  resources:
  - a2aagents/status
  - a2aregistries/status
  verbs:
  - get
  - patch
  - update
